# Generated by Django 5.1.3 on 2024-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
