# Generated by Django 5.1.3 on 2024-12-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
