# Generated by Django 5.1.3 on 2024-12-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
    ]
