# Generated by Django 5.1.3 on 2024-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
