# Generated by Django 5.1.3 on 2024-12-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profile_profile_img_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
