# Generated by Django 5.1.3 on 2024-12-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_room_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
    ]
