# Generated by Django 5.1.3 on 2024-12-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_room_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_age',
        ),
    ]
