# Generated by Django 5.1.3 on 2025-01-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_room_room_image_room_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_image',
            old_name='room',
            new_name='room_pic',
        ),
    ]
