# Generated by Django 5.1.3 on 2025-01-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_room_room_image_room_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_image',
            old_name='room_pic',
            new_name='room',
        ),
    ]
