# Generated by Django 5.1.3 on 2025-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_room_pic_room_image_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pendin', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='Pending', max_length=10),
        ),
    ]
